### ISSUE TITLE
PlantSideLocker.lua

### ISSUE THREAD

**Issue by dzagu** [Quake1011/CS2-plugins-lua#11]
Do u have config for mirage?
Is this script working? Kill announcer with distance print

**Comment by Quake1011** [comment]
What u means?

**Comment by Quake1011** [comment]
> Do u have config for mirage? Is this script working? Kill announcer with distance print

What u means

**Comment by dzagu** [comment]
Config with de_mirage BlockerPasses.ini

**Comment by dzagu** [comment]
And is this script Kill announcer with distance print working?

**Comment by Quake1011** [comment]
> Config with de_mirage BlockerPasses.ini

U created issue named PlantSideLocker, but asking about BlockerPasses... what the. I haven't config for it. Make it self! Kill distance working
