### ISSUE TITLE
Advertisment + Events

### ISSUE THREAD

**Issue by jovicdev97** [Quake1011/CS2-plugins-lua#13]
Hi!

all messages from advertisment are doubled on my server somehow.

events: sometimes only posts connect announce single time, sometime spam the server and send it 6-7x. idk why tho.

i did not had this problem a few days ago ... could it be related to csharp installed?

i dont have real useful information or logs here, as this problem appeared from nowhere.

installed plugins: csharp

**Comment by Quake1011** [comment]
Hi. This is a known problem and I do not know how to help you with it. Some people solved it by installing LuaLoader, for some it disappeared by itself. I personally have no such problems and never had

**Comment by asdfxD** [comment]
same issue with events and connect announce, happens sometimes when a player connect. i dont have csharp installed.

for example:

player2 joined the game
player2 left the game
player2 joined the game
