### ISSUE TITLE
How to use blocker passes

### ISSUE THREAD

**Issue by Veeksi** [Quake1011/CS2-plugins-lua#16]
Hey,

Could you provide a guide how can I use BlockerPasses? I would like to add invisible wall in the map so people cannot pass middle point but I have no idea how can I do so. 

Btw, I love the Refiller and Advertisement plugins!

**Comment by Quake1011** [comment]
Use BPEdit, after that spawn enough props via BPSpawn and print to console all spawned coordinates uses BPGen

**Comment by Veeksi** [comment]
> Use BPEdit, after that spawn enough props via BPSpawn and print to console all spawned coordinates uses BPGen

Do you know, is there fence or something that is invisible? So you can add fence that doesn't show up and doesn't block bullets, but blocks player

**Comment by Quake1011** [comment]
> > Use BPEdit, after that spawn enough props via BPSpawn and print to console all spawned coordinates uses BPGen
> 
> Do you know, is there fence or something that is invisible? So you can add fence that doesn't show up and doesn't block bullets, but blocks player

 All inclusive by default setting, u need just to change the alpha less then 255
