### ISSUE TITLE
colors bug

### ISSUE THREAD

**Issue by originalaidn** [Quake1011/CS2-plugins-lua#2]
sometimes colors aren't working. the tags everywhere uses darkgreen and the ---------- uses yellow
![colors](https://github.com/Quake1011/CS2-plugins-lua/assets/45371311/da487c16-770c-48b8-9e60-a39c823ec4ad)

**Comment by Quake1011** [comment]
Try adding a space before the whole text with the first character

**Comment by originalaidn** [comment]
yes, that was the problem. thanks a lot
