### ISSUE TITLE
ammo refill

### ISSUE THREAD

**Issue by Aliyuyu** [Quake1011/CS2-plugins-lua#3]
After the game is over and the map is changed, ammo refill does not work.

**Comment by Quake1011** [comment]
> After the game is over and the map is changed, ammo refill does not work.

Just a minute ago I checked after your message - everything is working fine

**Comment by Aliyuyu** [comment]
> > After the game is over and the map is changed, ammo refill does not work.
> 
> Just a minute ago I checked after your message - everything is working fine

Plugin default settings
https://youtu.be/rGQQULYZmXY

**Comment by Quake1011** [comment]
> > > After the game is over and the map is changed, ammo refill does not work.
> > 
> > Just a minute ago I checked after your message - everything is working fine
> 
> Plugin default settings https://youtu.be/rGQQULYZmXY

send friend discord quake1011

UPD: It was approver and i will fix it in future
