### ISSUE TITLE
double messages

### ISSUE THREAD

**Issue by duncosta** [Quake1011/CS2-plugins-lua#4]
Hi , all the ads appear duplicates, and I can't figure out why.

![Screenshot_5](https://github.com/Quake1011/CS2-plugins-lua/assets/75456318/fc795365-6a2f-4de9-b696-1ecb73ec25a1)
![Screenshot_4](https://github.com/Quake1011/CS2-plugins-lua/assets/75456318/0a7789c3-0614-48f8-ae2c-748895e1caca)
![Screenshot_6](https://github.com/Quake1011/CS2-plugins-lua/assets/75456318/748cbe8f-894b-4473-b14c-b3ad1fb25740)

**Comment by Quake1011** [comment]
You loaded plugin 2 times. Is it your wrong

**Comment by duncosta** [comment]
You were right, I put in gamemode_deathmatch.cfg and in gamemode_deathmatch_server.cfg :)). Thank you
