### ISSUE TITLE
Not working with Retakes mode

### ISSUE THREAD

**Issue by alincupunct** [Quake1011/CS2-plugins-lua#5]
I'm using the script on a competitive server, it's working fine, but on my 2 retakes servers nothing works (using it mainly for messages in the chat but other features don't work either).

**Comment by Quake1011** [comment]
if you are creating an issue, then please describe the problem!

**Comment by alincupunct** [comment]
If the server is running with sv_skirmish_id 12 (retakes mode), the script simply does not work, if I remove the sv_skirmish_id from the start line it works.
