### ISSUE TITLE
Kill distance doesnt work since the new version.

### ISSUE THREAD

**Issue by Monsterrko** [Quake1011/CS2-plugins-lua#6]
Hey man, since i updated the plugin from the very first released one. I dont see the kill distance being printed in chat. Other stuff is getting printed as it should and everythings working but this. 

Also i would like to know how to fix the nextmap: unknown. I guess i have to set some command or anything but dont know which one.
![image](https://github.com/Quake1011/CS2-plugins-lua/assets/145286280/dfaf4085-f4b8-49cb-ac37-2e286fdc6bc3)

**Comment by Monsterrko** [comment]
![image](https://github.com/Quake1011/CS2-plugins-lua/assets/145286280/86a70877-d600-4c9f-a209-285f07920384)

This is how i have it written in the config file.

**Comment by Quake1011** [comment]
Solved
