### ISSUE TITLE
weapondeleter issue

### ISSUE THREAD

**Issue by rcon420** [Quake1011/CS2-plugins-lua#7]
Script Runtime Error: ...l Offensive\game\csgo\scripts\vscripts\WeaponDeleter.lua:6: Cant load scripts/configs/WeaponDeleter.ini
stack traceback:
        [C]: in function 'error'
        ...l Offensive\game\csgo\scripts\vscripts\WeaponDeleter.lua:6: in function 'runscript'
        scripts\vscripts\utils/vscriptinit.lua:70: in function <scripts\vscripts\utils/vscriptinit.lua:58>

**Comment by Quake1011** [comment]
Describe the issue if u want gets help from me. Idk what the your vscriptinit.lua script

**Comment by Quake1011** [comment]
fixed
